# Generated by Django 5.1.5 on 2025-02-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainboosters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='child_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='child_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='child_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
