# Generated by Django 5.1.5 on 2025-02-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainboosters', '0002_parentprofile_name_tutorprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Ph.D.', 'Ph.D.')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='method',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
