# Generated by Django 5.1.5 on 2025-02-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainboosters', '0003_alter_tutorprofile_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='method',
            field=models.CharField(blank=True, choices=[('In-Person', 'In-Person'), ('Online', 'Online'), ('Online & In-Person', 'Online & In-Person')], max_length=20, null=True),
        ),
    ]
